project:
  type: website
  output-dir: docs

website:
  title: "Нинжин манал ӨЭМТ"
  site-url: "https://jamsranjamts.github.io/family-medicine-health-education/"
  favicon: assets/logo/logo-small.png
  search: true
  back-to-top-navigation: true
  page-footer:
    left: "© АШУҮИС, оюутан Ш.Жамсранжамц"
    center: "Нинжин манал ӨЭМТ"
    right: "Яаралтай тусламж: 103"
  navbar:
    logo: assets/logo/logo-transparent.png
    background: primary
    left:
      - href: index.qmd
        text: "Нүүр"
      - href: stroke.qmd
        text: "Тархины харвалт"
      - href: heart-attack.qmd
        text: "Зүрхний шигдээс"
      - href: epilepsy.qmd
        text: "Эпилепси"
      - href: kidney-failure.qmd
        text: "Бөөр"
      - href: autism.qmd
        text: "Аутизм"
      - href: post-stroke-exercises.qmd
        text: "Дасгал"
      - href: pressure-injury.qmd
        text: "Холголт"
      - href: downloads.qmd
        text: "QR татах"
      - href: references.qmd
        text: "Эх сурвалж"

resources:
  - assets/**
  - qr/**
  - print/**

format:
  html:
    theme: cosmo
    css: [styles.css, print.css]
    toc: true
    toc-depth: 3
    smooth-scroll: true
    page-layout: full
    code-tools: false

