
project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "print/*.qmd"

website:
  title: "Нинжин манал ӨЭМТ"
  navbar:
    logo: "assets/logo/ninjin_manal_logo.png"
    title: "Нинжин манал ӨЭМТ"
    background: light
    left:
      - text: "Нүүр"
        href: index.qmd
      - text: "Тархины харвалт"
        href: stroke.qmd
      - text: "Зүрхний шигдээс"
        href: heart-attack.qmd
      - text: "Эпилепси"
        href: epilepsy.qmd
      - text: "Бөөр"
        href: kidney-failure.qmd
      - text: "Аутизм"
        href: autism.qmd
      - text: "Дасгал"
        href: post-stroke-exercises.qmd
      - text: "Холголт"
        href: pressure-injury.qmd
      - text: "QR татах"
        href: qr-codes.qmd
      - text: "Эх сурвалж"
        href: references.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    page-layout: full
    lang: mn
    smooth-scroll: true

